### PR TITLE
Vacant/add to journey

### PR DESCRIPTION
**Pull request by aneves**
### All Submissions:

- [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### Tested Changes:

1. [x] Have you lint your code (lua lint) locally prior to submission?

Oh yes, I linted it good...

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully ran tests with your changes locally?

### Comments

Ran locally, with module enabled and with module disabled. Medium confidence.

This adds a setting to allow ignoring some surfaces - players that left on those surfaces are ignored.
This then makes the Mothership surface ignored on Journey.
Forgive me, Mother, for I have sinned.

This also adds documentation to the module.

---

This replaces PR #377 - second part, adding to Journey.
This lands on top of PR #379 .

The part about bodies not expiring has been excluded for now.

### CODE REVIEW

**Comment by aneves** [comment]
As draft for now, just waiting for PR #379 .
Because this one is built on top of it, and so it includes the same commits.

It's ready for review, but I think it's better to let the other one flow first, which will exclude those commits from here.

**Comment by Gerkiz** [comment]
I think @M3wM3w should review this since it is their scenario :}

**Comment by aneves** [comment]
I agree, M3wM3w should gate-keep these changes.
I offer them gratefully 💌 , they are yours to keep change or discard.

Let me know if there's any changes corrections or explanations that you would like.

**Comment by M3wM3w** [comment]
I am not sure why this would be needed. This is an issue of the game in general. Players leaving and "locking away" items. I am not conviced about this addition, since this is simply part of vanilla mechanics. This module should either be bound to the core scenario for all maps or none at all, since it is a vanilla multiplayer "flaw" in general.

**Comment by M3wM3w** [comment]
Don't get me wrong here. I am sure it's a good module. However, i am not sure why it should be part of just this map.

**Comment by aneves** [comment]
No no, I see your point completely.

I could bind the module to the core scenario for all maps, if you feel that it's better _and_ that it's a useful addition. :)
This PR requires (commented) the module in config.lua and then activates its journey-specific actions only if it's loaded. (It's still a bit coupled, enables and sets nauvis as main surface - which could be implicit.)
Do you mean different from this? If so, I can ask for clarifications in discord#opendev .


The functionality is used in other maps. Not in a lot of places, not yet.

The module is used in mountain_fortress_v3.

A version of this is used in Chrono.
That's where I learned about this addition, and where the idea to make it compatible with Journey came from. I was told that this module exists, so I tried to use it instead of duplicating the Chrono code.
In Chrono, players drop their body 72k ticks after leaving: `offline_players()` in [tick_functions.lua#L348](https://github.com/ComfyFactory/ComfyFactorio/blob/develop/maps/chronosphere/tick_functions.lua#L348).
I personally feel that this really reduces the friction from hoarding resources in multiplayer (either the player stays and contributes, and the hoarding is not a problem, or they leave and the items drop back to the team); and that it then really improves the cooperation and reduces unpleasantness.
In Journey, some resources are excessively rare. If some player leaves with electric furnaces early game, that can be a mission-critical problem.
Even other resources are often quite rare, as you know it has a grindy meta that balances progression with pollution/evo. Then, a player leaving with e.g. a MK2 is a big dent in the team's pool of items... and to be fair, this now opens a different can of worms: an experienced and very frequent player losing their MK2 while sleeping because someone else died with it next to a behemoth worm is a very bad penalty for the team too, and that should be considered when thinking about adding/activating this on Journey.
I understand these and other complications, and that it's not "yeah man let's just simply add it".

So I included the module in Journey as optional.
It is not added to journey unless it is included/uncommented in control.lua.
And if it is included, it can be toggled off by an admin in the UI config which was merged in PR 379: [utils/gui/config.lua](https://github.com/ComfyFactory/ComfyFactorio/pull/379/files#diff-30096f2ef3426e509648c9ed6b554c501fe42e10f2ad045cf5bb82a348e5da34)

---

There are similar but different applications in other maps.
But I feel that these represent _completely different use cases_: not about "keeping rare resources in the team", but about "keeping balance when quitting teams (switching, spectating, being jailed)":
- "A version of it" is used in pirates (when spectating, leaving crew, being jailed), to keep resources in the team pool: `function Public.send_important_items_from_player_to_crew(player, all_items)`, in [common.lua#L1287](https://github.com/ComfyFactory/ComfyFactorio/blob/develop/maps/pirates/common.lua#L1287).
- In biter battles, when switching force (team_manager.lua).

**Comment by hanakocz** [comment]
> Don't get me wrong here. I am sure it's a good module. However, i am not sure why it should be part of just this map.

Mew, the issue kinda is that some scenarios require special handling. Module got extracted from Chrono/MF/Pirates so it can be used on any map, and it should work on "vanilla-like" scenarios from the get go, but Journey requires something on top of it. To deal with Mothership restrictions on items (can't take them inside) and to be sure the things from creative chests inside Mothership won't get dropped on logout. On top of that, discard all items from memory on world change, and to make it switch the module onto new world. Regular maps don't require those additional steps, advanced maps do (and this PR is mostly about making those additional changes).

The mechanics is already used in Pirates, MF, Chrono (and maybe few more already), and the module was extracted from those gamemodes fairly recently so it can be used on any map, so the long term goal definitely is to include it into all maps, once the special cases are solved.

**Pull request closed without merging**
