### PR TITLE
add suicide command (for Towny)

### PR DESCRIPTION
**Pull request by fuchsnj**
This adds a `/suicide` command to Towny. This is useful since it's possible to trap players to the point where it's virtually impossible to play the game, such as the following example:

image

### CODE REVIEW

**Comment by Gerkiz** [comment]
Hi and thank you for your PR.

I would like to see some cooldown or max allowance. Since as of now - this is abusable.

Example:
Player runs the command. A cooldown is set for the given player so they cannot run it for say a couple of hours?

**Comment by blubFisch** [comment]
Good feature, but yes some sort of anti-abuse will be needed. I was thinking, once someone runs the command, we put a 10min timer together with a game.print before the .die() is called.

Trapping outlanders in Towny is quite fun and acts as a "prison" mechanic for "naked" outlanders that run around sabotaging your installations. So I want to leave it possible for the other side too.

**Comment by fuchsnj** [comment]
> Trapping outlanders in Towny is quite fun and acts as a "prison" mechanic for "naked" outlanders that run around sabotaging your installations.

I agree it's fun for a few minutes, until you realize you can't play the game at all. A 10 minute timer seems reasonable, I'll look into adding that soon.

**Comment by fuchsnj** [comment]
@blubFisch A 10 minute (+- 30 secs)  timer was added between when you call the `/suicide` command, and when you actually die. The player gets a countdown every minute.

**Comment by blubFisch** [comment]
Yeah generally looks good to me, thanks!

A cleaner and more lightweight variant would be to use a tick scheduler (which is only active when needed, unlike the main schedules in main.lua), there are some examples in the rest of the code (search for schedule, tick, timer, event or something).

**Comment by blubFisch** [comment]
Awesome, looks good to merge to me!

**Comment by blubFisch** [comment]
Ah, please add a line in info.lua about this.

**Comment by blubFisch** [comment]
@Gerkiz I'm happy for this to be merged as is

**Pull request merged**
