### PR TITLE
Fix for Journey: Fix teleporter not working when tiles are placed over it

### PR DESCRIPTION
**Pull request by Piratux**
### All Submissions:

- [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### Tested Changes:

1. [x] Have you lint your code (lua lint) locally prior to submission?

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully ran tests with your changes locally?

### Comments

Teleporter in journey does not work when tiles are placed over it.
This PR fixes it by checking for distance to teleporter instead.

### CODE REVIEW

**Comment by hanakocz** [comment]
why it also has a change for pirates, did you mix two things together?

also wouldn't be easier to just also check hidden tile rather than coords

**Comment by Piratux** [comment]
Hmm, I'm honestly not sure how the pirate changes got in there lol.
I wanted to get up to date version of comfy, but somehow got daniel's version too.

I wasn't aware that you can check for hidden tiles, but I don't think there is much of a difference here.
Also, I noticed that conflicts must be resolved before it can attempt to build?

**Comment by hanakocz** [comment]
Well gotta reverse pr from main to your fork occasionally :) https://github.com/ComfyFactory/ComfyFactorio/network
Conflict probably is a thing that gerkiz can deal with, but usually easier to just redo from the new fork in my opinion (but I hate git conflicts so I just avoid them).

**Comment by hanakocz** [comment]
Closing this, I will introduce even more merge conflicts with the journey update, and therefore it is easier to fix the issue as a part of update than solving merge conflicts and the pirate added thingie too. Though I am still unsure if the fix will be this way or the other, I am now considering to change the spawnpoint a bit more at this moment too as well (size and location and such)

Ha, also funny, just tried stuff, if you just nuke the elevator, it just removes the tiles forever and no elevator anymore :)))

**Pull request closed without merging**
