### PR TITLE
Dungeons 1.1.1 - Rebalance based on main Comfy server playthrough

### PR DESCRIPTION
**Pull request by eric-anderson**
### All Submissions:

- [YES] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### Tested Changes:

1. [YES] Have you lint your code (lua lint) locally prior to submission?

### Changes to Core Features:

- [YES] Have you added an explanation of what your changes do and why you'd like us to include them?
	{ ver = '1.1.1', date = '2022-04-10', desc = [[
Balancing patch
* Evolution goes up faster with floor level 0.05/level -> 0.06/level; e.g. floor 20 now like floor 24 before
* Now require 100 open rooms to descend
* Treasure rooms
  * Occur less frequently as each subsequent one is found. was 1 in 30 + 10*Nfound now 1 in 30 + 15*Nfound
  * Rebalanced ores to match end-game science needs. Was very low on copper
* Loot
  * Ammo/follower robot frequency ~0.5x previous
  * Loot is calculated at floor evolution * 0.9
  * Loot/box down by 0.75x
* Rocks
  * Ore from rocks from 25 + 25*floor to 40 + 15*floor capped at floor 15
  * Rebalanced to include ~10% more coal to give coal for power
* Require getting to room 100 before you can descend
* Science from rooms 40-160+2.5*floor to 60-300+2.5*floor
* Atomic bomb research moved to 40-50
]]},
- [YES] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by hanakocz — APPROVED** [review]
Looks good to me, though it definitely will be more grindy if someone wants to solo play it, but then, they probably should feel free to edit the script anyways :)

**Comment by eric-anderson** [comment]
> Looks good to me, though it definitely will be more grindy if someone wants to solo play it, but then, they probably should feel free to edit the script anyways :)

Yes, I'm balancing for the multiplayer runs. Once I'm done finding things to balance and move the configs to the top, I can do the same thing other modes do of having difficulty.

**Comment by eric-anderson** [comment]
Huh, that's not what I thought that button would do in replying.

**Comment by hanakocz** [comment]
Don't worry about singleplayer scaling unless we explicitly support it (for example via config tab, or scenarios that have difficulty vote), then it just isn't worth to have, it is easier to tell people what to change to get better scaling for their private use :)

**Comment by Gerkiz** [comment]
LGTM!

**Pull request merged**
